(define-module (lotus-rde lib utils)
  #:use-module (ice-9 match)
  #:use-module (ice-9 hash-table)
  #:use-module (ice-9 format)
  #:use-module (ice-9 popen)
  #:use-module (ice-9 ftw)
  #:use-module (ice-9 threads)
  #:use-module (srfi srfi-1)
  #:use-module (srfi srfi-11)
  #:use-module (srfi srfi-13)
  #:use-module (guix gexp)
  #:use-module (guix modules)
  #:use-module (guix build utils)
  #:use-module (gnu system mapped-devices)
  #:use-module (gnu system file-systems)
  #:use-module (gnu system uuid)
  #:use-module (gnu packages linux)
  #:export (lotus-assert))

(define (lotus-assert condition . msg)
  (throw-message
   condition
   (if (null? msg)
       (list "Assertion failed")
       msg)))
